/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery.register;

import fooddelivery.Use.Login;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.IOException;
import java.sql.DriverManager;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class NewMerchant extends javax.swing.JFrame {

    private static NewMerchant instance;

    public static NewMerchant getInstance() {
        if (instance == null) {
            instance = new NewMerchant();
        }
        return instance;
    }

    public NewMerchant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jt6 = new javax.swing.JTextField();
        jt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt7 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jB1 = new javax.swing.JComboBox();
        jB3 = new javax.swing.JComboBox();
        jB4 = new javax.swing.JComboBox();
        jB2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Store name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 40));

        jt6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt6ActionPerformed(evt);
            }
        });
        getContentPane().add(jt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 214, 30));

        jt5.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt5ActionPerformed(evt);
            }
        });
        getContentPane().add(jt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 214, -1));

        jLabel6.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Phone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 40));

        jLabel7.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Business category:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 49));

        jLabel8.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Store area:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("detailed address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, -1));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Welcome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, 50));

        jLabel5.setFont(new java.awt.Font("微软雅黑", 2, 110)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("F");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 70, 160));

        jLabel10.setFont(new java.awt.Font("微软雅黑", 2, 70)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 51));
        jLabel10.setText("at?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 110, 80));

        jLabel11.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(81, 64, 130));
        jLabel11.setText("basic information");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jt7.setColumns(20);
        jt7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jt7.setRows(5);
        jScrollPane1.setViewportView(jt7);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 220, 60));

        jLabel12.setFont(new java.awt.Font("微软雅黑 Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(81, 64, 130));
        jLabel12.setText("You need to complete the basic information filling, menu creation to complete business registration ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("微软雅黑 Light", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(81, 64, 130));
        jLabel13.setText("Business registration");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("微软雅黑 Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(81, 64, 130));
        jButton1.setText("Submit to the next step: menu creation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "选择城市", "海口", "三亚", "三沙", "五指山" }));
        jB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jB1ItemStateChanged(evt);
            }
        });
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "选择街道", "人民大道", "和平大道", "三西路", "五西路", "安民路", "蓝田街道" }));
        jB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jB3ItemStateChanged(evt);
            }
        });
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, 20));

        jB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "美食", "超市", "饮品", "生鲜" }));
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 20));

        jB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "选择地区" }));
        jB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jB2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 80, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/登陆背景图.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt6ActionPerformed

    private void jt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            PreparedStatement pst2;//预先声明
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fooddelivery", "root", "1234");//定义连接
            String sql2 = "insert into merchant values(?,?,?,?,?,?,?)";//SQL命令
            pst2 = (PreparedStatement) con.prepareStatement(sql2);//创建声明连接
            pst2.setString(1, jt5.getText());//获得数值
            pst2.setString(3, jt6.getText());//电话
            pst2.setString(2, jB4.getSelectedItem().toString());//经营品类
            pst2.setString(7, jt7.getText());//详细地址
            pst2.setString(4, jB1.getSelectedItem().toString());//市
            pst2.setString(5, jB2.getSelectedItem().toString());//区
            pst2.setString(6, jB3.getSelectedItem().toString());//街道
            if (jt5.getText().equals(null) || jt6.getText().equals(null) || jt7.getText().equals(null) ) {
                JOptionPane.showMessageDialog(null, "您还有信息未填写完整");}
                else{
            pst2.executeUpdate();//数据更新
            
            JOptionPane.showMessageDialog(null, "注册成功！");
            this.hide();
            NewMenu newmenu = NewMenu.getnw();
            newmenu.pack();
            newmenu.setLocationRelativeTo(null);
            newmenu.setVisible(true);
            newmenu.show();
            this.hide();
            };
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "您已经注册过了");
        }





    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jB1ItemStateChanged
        // TODO add your handling code here:
        String item = evt.getItem().toString();
        jB2.removeAllItems();
        if (item.equals("海口")) {
            jB2.addItem("美兰区");
            jB2.addItem("秀英区");
            jB2.addItem("龙华区");
            jB2.addItem("琼山区");

        }
        if (item.equals("三亚")) {
            jB2.addItem("海棠区");
            jB2.addItem("吉阳区");
            jB2.addItem("天崖区");
            jB2.addItem("崖州区");
        }
    }//GEN-LAST:event_jB1ItemStateChanged

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jB3ItemStateChanged
   }//GEN-LAST:event_jB3ItemStateChanged

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jB2ItemStateChanged
        String item = evt.getItem().toString();
        jB3.removeAllItems();
        if (item.equals("美兰区")) {
            jB3.addItem("人民大道");
            jB3.addItem("和平大道");
            jB3.addItem("三西路");
            jB3.addItem("五西路");
            jB3.addItem("安民路");
            jB3.addItem("蓝田街道");//人民大道, 和平大道, 三西路, 五西路, 安民路, 蓝田街道
        }
    }//GEN-LAST:event_jB2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login login = new Login();
        login.pack();
        login.setLocationRelativeTo(null);
        this.hide();
        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMerchant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMerchant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMerchant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMerchant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewMerchant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jB1;
    private javax.swing.JComboBox jB2;
    private javax.swing.JComboBox jB3;
    private javax.swing.JComboBox jB4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextArea jt7;
    // End of variables declaration//GEN-END:variables
}
