/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery.Order;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import fooddelivery.Use.Login;
import fooddelivery.Use.Welcome;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jt3 = new javax.swing.JTextField();
        jt1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        getContentPane().add(jt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 200, 30));

        jLabel3.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Phonenumber:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 40));

        jLabel4.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 50));

        jLabel6.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 40));

        jt2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        getContentPane().add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, 30));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, 50));

        jLabel9.setFont(new java.awt.Font("微软雅黑 Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("The delivery time:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("微软雅黑", 2, 110)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("F");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 70, 150));

        jLabel7.setFont(new java.awt.Font("微软雅黑", 2, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("at?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 110, 80));

        jLabel11.setFont(new java.awt.Font("微软雅黑 Light", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(81, 64, 130));
        jLabel11.setText("Make sure the Order");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(81, 64, 130));
        jButton1.setText("Place the order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 210, 30));

        jt3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        getContentPane().add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, 30));

        jt1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        getContentPane().add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/登陆背景图.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            PreparedStatement pst2;//预先声明
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fooddelivery", "root", "1234");//定义连接
            String sql2 = "insert into OrderInformation values(?,?,?,?)";//SQL命令
            pst2 = (PreparedStatement) con.prepareStatement(sql2);//创建声明连接
            pst2.setString(1, jt1.getText());//获得数值
            pst2.setString(2, jt2.getText());
            pst2.setString(3, jt3.getText());
            pst2.setString(4, jt4.getText());//获得数值
            if (jt2.getText().equals(null) || jt3.getText().equals(null) || jt1.getText().equals(null) || jt4.getText().equals(null)) {
                 JOptionPane.showMessageDialog(null, "您有信息未填写");
            } else {
               
                pst2.executeUpdate();//数据更新
                JOptionPane.showMessageDialog(null, "下单成功！祝您用餐愉快");
                this.hide();
                Welcome welcome = new Welcome();
                welcome.pack();
                welcome.setLocationRelativeTo(null);
                welcome.setVisible(true);
            };
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "您还有信息未填写完整");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Order().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    // End of variables declaration//GEN-END:variables
}
